"""initial schema

Revision ID: 0a73092310ae
Revises: 
Create Date: 2026-08-27 17:36:59.616016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a73092310ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sound_master_volume', sa.Integer(), nullable=False),
    sa.Column('sound_tink_enabled', sa.Boolean(), nullable=False),
    sa.Column('sound_warnings_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_settings'))
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('name', name=op.f('uq_leagues_name'))
    )
    op.create_table('divine_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('chaos_value', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_divine_rates_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divine_rates'))
    )
    op.create_table('gold_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('gold_amount', sa.Integer(), nullable=False),
    sa.Column('chaos_value', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_gold_rates_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gold_rates'))
    )
    op.create_table('trading_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('closed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_trading_days_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_days'))
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('trading_day_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('entered_price', sa.Integer(), nullable=False),
    sa.Column('unit_price_chaos', sa.Integer(), nullable=False),
    sa.Column('quantity_bought', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('gold_spent', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_trades_league_id_leagues')),
    sa.ForeignKeyConstraint(['trading_day_id'], ['trading_days.id'], name=op.f('fk_trades_trading_day_id_trading_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('trading_day_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('entered_price', sa.Integer(), nullable=False),
    sa.Column('unit_price_chaos', sa.Integer(), nullable=False),
    sa.Column('total_chaos', sa.Integer(), nullable=False),
    sa.Column('cost_chaos', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=False),
    sa.Column('gold_received', sa.Integer(), nullable=False),
    sa.Column('sold_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_sales_trade_id_trades')),
    sa.ForeignKeyConstraint(['trading_day_id'], ['trading_days.id'], name=op.f('fk_sales_trading_day_id_trading_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('trades')
    op.drop_table('trading_days')
    op.drop_table('gold_rates')
    op.drop_table('divine_rates')
    op.drop_table('leagues')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
