"""add active league name to global settings

Revision ID: 17c45ee4c043
Revises: 928b491c71c8
Create Date: 2026-08-28 00:29:33.413832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c45ee4c043'
down_revision: Union[str, Sequence[str], None] = '928b491c71c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_league_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('active_league_name')

    # ### end Alembic commands ###
