"""add sound tier thresholds to global settings

Revision ID: 39fd57b9e9a6
Revises: 8320825e4f2b
Create Date: 2026-08-27 18:30:11.144206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fd57b9e9a6'
down_revision: Union[str, Sequence[str], None] = '8320825e4f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here: SQLite can't add a NOT NULL
    # column with no default to a table that may already have rows.
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'sound_tier_small_max', sa.Integer(),
                nullable=False, server_default='200'
            )
        )
        batch_op.add_column(
            sa.Column(
                'sound_tier_medium_max', sa.Integer(),
                nullable=False, server_default='800'
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('sound_tier_medium_max')
        batch_op.drop_column('sound_tier_small_max')

    # ### end Alembic commands ###
