"""add assets table and trade asset_id

Revision ID: 8320825e4f2b
Revises: 0a73092310ae
Create Date: 2026-08-27 18:03:58.063863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8320825e4f2b'
down_revision: Union[str, Sequence[str], None] = '0a73092310ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('icon_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('external_id', name=op.f('uq_assets_external_id'))
    )
    # SQLite can't ALTER a foreign key constraint onto an existing
    # table directly — batch mode recreates the table instead.
    with op.batch_alter_table('trades') as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            op.f('fk_trades_asset_id_assets'), 'assets', ['asset_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades') as batch_op:
        batch_op.drop_constraint(
            op.f('fk_trades_asset_id_assets'), type_='foreignkey'
        )
        batch_op.drop_column('asset_id')
    op.drop_table('assets')
    # ### end Alembic commands ###
