"""add trading day history snapshot columns

Revision ID: 928b491c71c8
Revises: 39fd57b9e9a6
Create Date: 2026-08-27 22:32:55.441355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928b491c71c8'
down_revision: Union[str, Sequence[str], None] = '39fd57b9e9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_new_trades', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_carryover_sales', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_realized_profit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_roi', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_revenue', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_inventory_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_gold_spent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_average_profit_per_trade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_completed_trades', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_days', schema=None) as batch_op:
        batch_op.drop_column('snapshot_completed_trades')
        batch_op.drop_column('snapshot_average_profit_per_trade')
        batch_op.drop_column('snapshot_gold_spent')
        batch_op.drop_column('snapshot_inventory_value')
        batch_op.drop_column('snapshot_revenue')
        batch_op.drop_column('snapshot_roi')
        batch_op.drop_column('snapshot_realized_profit')
        batch_op.drop_column('snapshot_carryover_sales')
        batch_op.drop_column('snapshot_new_trades')

    # ### end Alembic commands ###
